package profile

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/ethanhq/cc-fleet/internal/config"
)

// sampleVendor returns a representative *config.Vendor used across tests.
func sampleVendor() *config.Vendor {
	return &config.Vendor{
		Name:           "deepseek",
		BaseURL:        "https://api.deepseek.com/anthropic",
		DefaultModel:   "deepseek-v4-flash",
		ModelsEndpoint: "https://api.deepseek.com/v1/models",
		SecretBackend:  "file",
		SecretRef:      "deepseek.key",
		Enabled:        true,
		AddedAt:        time.Date(2026, 5, 24, 0, 0, 0, 0, time.UTC),
	}
}

// isolateHome points $HOME at a temp dir so ProfilesDir() is sandboxed.
func isolateHome(t *testing.T) string {
	t.Helper()
	home := t.TempDir()
	t.Setenv("HOME", home)
	return home
}

func TestGenerateForVendor_Snapshot(t *testing.T) {
	v := sampleVendor()
	const helper = "/usr/local/bin/cc-fleet"
	const want = `{
  "apiKeyHelper": "/usr/local/bin/cc-fleet keyget deepseek",
  "env": {
    "ANTHROPIC_BASE_URL": "https://api.deepseek.com/anthropic"
  }
}`

	got, err := GenerateForVendor(v, helper)
	if err != nil {
		t.Fatalf("GenerateForVendor: %v", err)
	}
	if strings.TrimSpace(string(got)) != strings.TrimSpace(want) {
		t.Fatalf("snapshot mismatch:\n--- got ---\n%s\n--- want ---\n%s\n", got, want)
	}

	// Reverse: produced bytes must parse as JSON and round-trip both fields.
	var back struct {
		APIKeyHelper string            `json:"apiKeyHelper"`
		Env          map[string]string `json:"env"`
	}
	if err := json.Unmarshal(got, &back); err != nil {
		t.Fatalf("Unmarshal generated bytes: %v", err)
	}
	if back.APIKeyHelper != helper+" keyget deepseek" {
		t.Fatalf("apiKeyHelper = %q, want %q", back.APIKeyHelper, helper+" keyget deepseek")
	}
	if back.Env["ANTHROPIC_BASE_URL"] != v.BaseURL {
		t.Fatalf("env[ANTHROPIC_BASE_URL] = %q, want %q",
			back.Env["ANTHROPIC_BASE_URL"], v.BaseURL)
	}
}

func TestGenerateForVendor_RejectsBadInputs(t *testing.T) {
	cases := []struct {
		name   string
		v      *config.Vendor
		helper string
	}{
		{"nil vendor", nil, "/abs/cc-fleet"},
		{"empty name", &config.Vendor{BaseURL: "https://x"}, "/abs/cc-fleet"},
		{"empty base_url", &config.Vendor{Name: "x"}, "/abs/cc-fleet"},
		{"empty helper", sampleVendor(), ""},
		{"relative helper", sampleVendor(), "cc-fleet"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if _, err := GenerateForVendor(tc.v, tc.helper); err == nil {
				t.Fatalf("GenerateForVendor(%+v, %q): want error, got nil", tc.v, tc.helper)
			}
		})
	}
}

func TestWriteForVendor_FilePerm(t *testing.T) {
	isolateHome(t)
	v := sampleVendor()

	path, err := WriteForVendor(v, "/usr/local/bin/cc-fleet")
	if err != nil {
		t.Fatalf("WriteForVendor: %v", err)
	}
	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("Stat: %v", err)
	}
	if got := info.Mode().Perm(); got != 0o600 {
		t.Fatalf("profile mode = %o, want 0600", got)
	}

	// Content sanity: matches GenerateForVendor output byte-for-byte.
	gotBytes, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	wantBytes, err := GenerateForVendor(v, "/usr/local/bin/cc-fleet")
	if err != nil {
		t.Fatalf("GenerateForVendor: %v", err)
	}
	if string(gotBytes) != string(wantBytes) {
		t.Fatalf("file content mismatch:\n--- file ---\n%s\n--- want ---\n%s\n",
			gotBytes, wantBytes)
	}
}

func TestWriteForVendor_Atomic_NoTempLeft(t *testing.T) {
	isolateHome(t)
	v := sampleVendor()

	if _, err := WriteForVendor(v, "/usr/local/bin/cc-fleet"); err != nil {
		t.Fatalf("WriteForVendor: %v", err)
	}
	dir, err := ProfilesDir()
	if err != nil {
		t.Fatalf("ProfilesDir: %v", err)
	}
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("ReadDir: %v", err)
	}

	var leaked []string
	for _, e := range entries {
		// CreateTemp inserts a random suffix between our prefix and ".tmp" —
		// the final 4 chars are always ".tmp" when our temp leaks.
		if strings.HasSuffix(e.Name(), ".tmp") {
			leaked = append(leaked, e.Name())
		}
	}
	if len(leaked) > 0 {
		t.Fatalf("temp files leaked: %v", leaked)
	}

	// And the real file is present.
	wantName := v.Name + ".json"
	var found bool
	for _, e := range entries {
		if e.Name() == wantName {
			found = true
			break
		}
	}
	if !found {
		t.Fatalf("expected %s in %s; got entries %v", wantName, dir, entries)
	}
}

func TestWriteForVendor_HelperBinaryEmpty_UsesExecutable(t *testing.T) {
	isolateHome(t)
	v := sampleVendor()

	exe, err := os.Executable()
	if err != nil {
		t.Fatalf("os.Executable: %v", err)
	}

	path, err := WriteForVendor(v, "")
	if err != nil {
		t.Fatalf("WriteForVendor: %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	var back struct {
		APIKeyHelper string `json:"apiKeyHelper"`
	}
	if err := json.Unmarshal(data, &back); err != nil {
		t.Fatalf("Unmarshal: %v", err)
	}
	want := exe + " keyget " + v.Name
	if back.APIKeyHelper != want {
		t.Fatalf("apiKeyHelper = %q, want %q", back.APIKeyHelper, want)
	}
}

func TestWriteForVendor_OverwriteExisting(t *testing.T) {
	isolateHome(t)
	v := sampleVendor()

	// First write.
	if _, err := WriteForVendor(v, "/old/path/cc-fleet"); err != nil {
		t.Fatalf("first WriteForVendor: %v", err)
	}
	// Second write with a different helper path so we can prove the file
	// content actually changed.
	path, err := WriteForVendor(v, "/new/path/cc-fleet")
	if err != nil {
		t.Fatalf("second WriteForVendor: %v", err)
	}
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	if !strings.Contains(string(data), "/new/path/cc-fleet keyget deepseek") {
		t.Fatalf("expected new helper path in file; got:\n%s", data)
	}
	if strings.Contains(string(data), "/old/path/cc-fleet") {
		t.Fatalf("old helper path leaked into rewritten file:\n%s", data)
	}
}

func TestRemoveForVendor_OK(t *testing.T) {
	isolateHome(t)
	v := sampleVendor()

	path, err := WriteForVendor(v, "/usr/local/bin/cc-fleet")
	if err != nil {
		t.Fatalf("WriteForVendor: %v", err)
	}
	if _, err := os.Stat(path); err != nil {
		t.Fatalf("Stat before remove: %v", err)
	}
	if err := RemoveForVendor(v.Name); err != nil {
		t.Fatalf("RemoveForVendor: %v", err)
	}
	if _, err := os.Stat(path); !os.IsNotExist(err) {
		t.Fatalf("expected file gone, got Stat err=%v", err)
	}
}

func TestRemoveForVendor_MissingNotError(t *testing.T) {
	isolateHome(t)
	if err := RemoveForVendor("never-existed"); err != nil {
		t.Fatalf("RemoveForVendor on missing: want nil, got %v", err)
	}
}

func TestProfilePath(t *testing.T) {
	home := isolateHome(t)
	got, err := ProfilePath("deepseek")
	if err != nil {
		t.Fatalf("ProfilePath: %v", err)
	}
	want := filepath.Join(home, ".claude", "profiles", "deepseek.json")
	if got != want {
		t.Fatalf("ProfilePath = %q, want %q", got, want)
	}
}

func TestProfilePath_EmptyVendor(t *testing.T) {
	isolateHome(t)
	if _, err := ProfilePath(""); err == nil {
		t.Fatalf("ProfilePath(\"\"): want error, got nil")
	}
}

func TestProfilesDir_NoHome(t *testing.T) {
	t.Setenv("HOME", "")
	if _, err := ProfilesDir(); err == nil {
		t.Fatalf("ProfilesDir: want error when HOME unset, got nil")
	}
}
